apiVersion: v1
kind: Pod
metadata:
  name: my-webserver-pod
  labels:
    name: my-webserver-pod
spec:
  containers:
  - name: my-webserver-container
    image: ngelders/rootsacademy-k8s-exercise:latest
    env:
    - name: COLOR
      value: "#0f0f00"
    ports:
    - containerPort: 8000